name: Deploy to Docker

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: maurisola/webpage-test:latest
        build_args: |
          HTML_FILE=index.html
        context: .
      
    - name: Run Docker container
      run: docker run -d -p 8080:80 maurisola/webpage-test:latest
